export const showjobs = [
  {
    image: "https://i.ibb.co/mSnGTbh/company-Logo.png",
    name: "Senior UX Designer",
    work: "Highspeed Studios",
    dollar_beg: "https://i.ibb.co/9hkfHHQ/icSalary.png",
    sallery: "$14,000 - $25,000",
    monthly: "Monthly Salary",
    location_icon: "https://i.ibb.co/85ThXnh/ic-Location.png",
    location: "London, England",
    location_text: "Location",
  },
  {
    image: "https://i.ibb.co/hLTMZ9h/company-Logo-1.png",
    name: "Intern UX Designer",
    work: "Maximoz Team",
    dollar_beg: "https://i.ibb.co/9hkfHHQ/icSalary.png",
    sallery: "$500 - $1000",
    monthly: "Monthly Salary",
    location_icon: "https://i.ibb.co/85ThXnh/ic-Location.png",
    location: "London, England, ",
    location_text: "Location",
  },
  {
    image: "https://i.ibb.co/JytcPXW/company-Logo.png",
    name: "Junior UX Designer",
    work: "Vvibu Leu Boz Studios",
    dollar_beg: "https://i.ibb.co/9hkfHHQ/icSalary.png",
    sallery: "$8,000 - $12,000",
    monthly: "Monthly Salary",
    location_icon: "https://i.ibb.co/85ThXnh/ic-Location.png",
    location: "Oxford, England",
    location_text: "Location",
  },
  {
    image: "https://i.ibb.co/cb3c0zt/company-Logo-1.png",
    name: "Principal UX Designer",
    work: "Vvibu Leu Boz Studios",
    dollar_beg: "https://i.ibb.co/9hkfHHQ/icSalary.png",
    sallery: "$11,000 - $60,000",
    monthly: "Monthly Salary",
    location_icon: "https://i.ibb.co/85ThXnh/ic-Location.png",
    location: "London, England",
    location_text: "Location",
  },
  {
    image: "https://i.ibb.co/khkYWjW/company-Logo-2.png",
    name: "Senior UX Designer",
    work: "Highspeed Studios",
    dollar_beg: "https://i.ibb.co/9hkfHHQ/icSalary.png",
    sallery: "$500 - $1,000",
    monthly: "Monthly Salary",
    location_icon: "https://i.ibb.co/85ThXnh/ic-Location.png",
    location: "London, England",
    location_text: "Location",
  },
  {
    image: "https://i.ibb.co/PrN8NJt/company-Logo-3.png",
    name: "Principal UX Designer",
    work: "Lowvoltages Team",
    dollar_beg: "https://i.ibb.co/9hkfHHQ/icSalary.png",
    sallery: "$11,00 - $60,000",
    monthly: "Monthly Salary",
    location_icon: "https://i.ibb.co/85ThXnh/ic-Location.png",
    location: "London, England",
    location_text: "Location",
  },
  {
    image: "https://i.ibb.co/G7mdbzv/company-Logo-4.png",
    name: "Senior UX Designer",
    work: "Highspedd Studios",
    dollar_beg: "https://i.ibb.co/9hkfHHQ/icSalary.png",
    sallery: "$500 - $1000",
    monthly: "Monthly Salary",
    location_icon: "https://i.ibb.co/85ThXnh/ic-Location.png",
    location: "London, England",
    location_text: "Location",
  },
  {
    image: "https://i.ibb.co/sqpSfxG/company-Logo-5.png",
    name: "Principal UX Designer",
    work: "Lowvoltages Team",
    dollar_beg: "https://i.ibb.co/9hkfHHQ/icSalary.png",
    sallery: "$11,00 - $60,000",
    monthly: "Monthly Salary",
    location_icon: "https://i.ibb.co/85ThXnh/ic-Location.png",
    location: "London, England",
    location_text: "Location",
  },
  {
    image: "https://i.ibb.co/7gx2nVF/company-Logo-6.png",
    name: "Senior UX Designer",
    work: "Highspeed Studios",
    dollar_beg: "https://i.ibb.co/9hkfHHQ/icSalary.png",
    sallery: "$500 - $1,000",
    monthly: "Monthly Salary",
    location_icon: "https://i.ibb.co/85ThXnh/ic-Location.png",
    location: "London, England",
    location_text: "Location",
  },
];

export const allPerson = [
  {
    id: 1,
    img: "https://i.ibb.co/Cz8JTqH/placeholder-1.png",
    name: "Angela Moss",
    profession: "Content Writer",
    starReview: 4.3,
    country: "New York, US",
    joining: "oct 2018",
    rate: "$50/hr",
    review: "4 Days ago",
    active: true,
  },
  {
    id: 2,
    img: "https://i.ibb.co/HtgnFSJ/placeholder-2.png",
    name: "Jimmy Lee",
    profession: "Programmer",
    starReview: 4.3,
    country: "Jakarta, Indoneisa",
    joining: "oct 2014",
    rate: "$26/hr",
    review: "4 Days ago",
    active: false,
  },
  {
    id: 3,
    img: "https://i.ibb.co/bmgrjfC/placeholder-3.png",
    name: "Melinda Humbles",
    profession: "Graphic Designer",
    starReview: 3.0,
    country: "New York",
    joining: "oct 2020",
    rate: "$92/hr",
    review: "4 Days ago",
    active: true,
  },
  {
    id: 4,
    img: "https://i.ibb.co/kc7LRJh/placeholder-4.png",
    name: "Jordan Sigh",
    profession: "Content Writer",
    starReview: 4.3,
    country: "New York",
    joining: "oct 2020",
    rate: "$38/hr",
    review: "4 Days ago",
    active: true,
  },
  {
    id: 5,
    img: "https://i.ibb.co/dQ8Nbmt/placeholder-5.png",
    name: "Mahmuda",
    profession: "Programmer",
    starReview: 4.3,
    country: "Jakarta, Indonesia",
    joining: "oct 2014",
    rate: "$26/hr",
    review: "4 Days ago",
    active: false,
  },
  {
    id: 6,
    img: "https://i.ibb.co/C2rQPPG/placeholder-6.png",
    name: "Roberto Karloz",
    profession: "Photographer",
    starReview: 3.0,
    country: "New York",
    joining: "oct 2020",
    rate: "$92/hr",
    review: "4 Days ago",
    active: true,
  },
  {
    id: 7,
    img: "https://i.ibb.co/f81f3QT/placeholder-7.png",
    name: "Gwen Claudya",
    profession: "Programmer",
    starReview: 4.3,
    country: "Jakarta Indonsia",
    joining: "oct 2014",
    rate: "$26/hr",
    review: "4 Days ago",
    active: false,
  },
  {
    id: 8,
    img: "https://i.ibb.co/j6kbqMy/placeholder-8.png",
    name: "Bella Smith",
    profession: "Content Writer",
    starReview: 4.3,
    country: "New York",
    joining: "oct 2020",
    rate: "$38/hr",
    review: "4 Days ago",
    active: true,
  },
  {
    id: 9,
    img: "https://i.ibb.co/ncVQYPP/placeholder-9.png",
    name: "Samantha William",
    profession: "Programmer",
    starReview: 4.3,
    country: "Jakarta, Indonesia",
    joining: "oct 2014",
    rate: "$26/hr",
    review: "4 Days ago",
    active: false,
  },
  {
    id: 10,
    img: "https://i.ibb.co/pZkLcdL/placeholder-10.png",
    name: "Kokom",
    profession: "Photgrapher",
    starReview: 3.0,
    country: "New York",
    joining: "oct 2020",
    rate: "$92/hr",
    review: "4 Days ago",
    active: true,
  },
  {
    id: 11,
    img: "https://i.ibb.co/fpwdXBt/placeholder-11.png",
    name: "Fanny Fancyson",
    profession: "Programmer",
    starReview: 4.3,
    country: "Jakarta, Indonesia",
    joining: "oct 2014",
    rate: "$92/hr",
    review: "4 Days ago",
    active: false,
  },
  {
    id: 12,
    img: "https://i.ibb.co/b1nPNhj/placeholder-12.png",
    name: "Louis Anderson",
    profession: "Content Writer",
    starReview: 4.3,
    country: "New York",
    joining: "oct 2020",
    rate: "$38/hr",
    review: "4 Days ago",
    active: true,
  },
];
